language: php
sudo: false
php:
  - 7.1
  - nightly
before_install:
  - phpenv rehash
install:
  - composer install
cache:
  directories:
   - $HOME/.composer/cache
script:
  # we do a simple lint
  - find . -type f -name '*.php' -print0 |xargs -0 -I file -P 4 php -l file > /dev/null
  # phpunit tests
  - vendor/bin/phpunit