language: php
sudo: false
php:
  - 7.1
  - nightly
before_install:
  - phpenv rehash
script:
  # we do a simple lint
  # TODO: Do some advanced testing here
  - find . -type f -name '*.php' -print0 |xargs -0 -I file -P 4 php -l file > /dev/null